# Generated by Django 4.0.4 on 2022-04-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_team_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='foo',
        ),
    ]
